// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iatafinder.proto

package iatafinder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Airport struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Iata                 string   `protobuf:"bytes,5,opt,name=iata,proto3" json:"iata,omitempty"`
	Icao                 string   `protobuf:"bytes,6,opt,name=icao,proto3" json:"icao,omitempty"`
	Latitude             float64  `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float64  `protobuf:"fixed64,9,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Timezone             string   `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	DaylightSavingsTime  string   `protobuf:"bytes,11,opt,name=daylight_savings_time,json=daylightSavingsTime,proto3" json:"daylight_savings_time,omitempty"`
	Tz                   string   `protobuf:"bytes,12,opt,name=tz,proto3" json:"tz,omitempty"`
	Type                 string   `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Airport) Reset()         { *m = Airport{} }
func (m *Airport) String() string { return proto.CompactTextString(m) }
func (*Airport) ProtoMessage()    {}
func (*Airport) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5d7323532d9adb, []int{0}
}

func (m *Airport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Airport.Unmarshal(m, b)
}
func (m *Airport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Airport.Marshal(b, m, deterministic)
}
func (m *Airport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Airport.Merge(m, src)
}
func (m *Airport) XXX_Size() int {
	return xxx_messageInfo_Airport.Size(m)
}
func (m *Airport) XXX_DiscardUnknown() {
	xxx_messageInfo_Airport.DiscardUnknown(m)
}

var xxx_messageInfo_Airport proto.InternalMessageInfo

func (m *Airport) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Airport) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Airport) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Airport) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Airport) GetIata() string {
	if m != nil {
		return m.Iata
	}
	return ""
}

func (m *Airport) GetIcao() string {
	if m != nil {
		return m.Icao
	}
	return ""
}

func (m *Airport) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Airport) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Airport) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Airport) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Airport) GetDaylightSavingsTime() string {
	if m != nil {
		return m.DaylightSavingsTime
	}
	return ""
}

func (m *Airport) GetTz() string {
	if m != nil {
		return m.Tz
	}
	return ""
}

func (m *Airport) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Airport) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Iata struct {
	Iata                 string   `protobuf:"bytes,1,opt,name=iata,proto3" json:"iata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Iata) Reset()         { *m = Iata{} }
func (m *Iata) String() string { return proto.CompactTextString(m) }
func (*Iata) ProtoMessage()    {}
func (*Iata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff5d7323532d9adb, []int{1}
}

func (m *Iata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iata.Unmarshal(m, b)
}
func (m *Iata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iata.Marshal(b, m, deterministic)
}
func (m *Iata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iata.Merge(m, src)
}
func (m *Iata) XXX_Size() int {
	return xxx_messageInfo_Iata.Size(m)
}
func (m *Iata) XXX_DiscardUnknown() {
	xxx_messageInfo_Iata.DiscardUnknown(m)
}

var xxx_messageInfo_Iata proto.InternalMessageInfo

func (m *Iata) GetIata() string {
	if m != nil {
		return m.Iata
	}
	return ""
}

func init() {
	proto.RegisterType((*Airport)(nil), "iatafinder.Airport")
	proto.RegisterType((*Iata)(nil), "iatafinder.Iata")
}

func init() { proto.RegisterFile("iatafinder.proto", fileDescriptor_ff5d7323532d9adb) }

var fileDescriptor_ff5d7323532d9adb = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4f, 0x6b, 0xf3, 0x30,
	0x0c, 0xc6, 0x5f, 0xe7, 0xed, 0x5f, 0x75, 0x2b, 0xc5, 0x65, 0x43, 0x94, 0x1d, 0x4a, 0x4f, 0x3d,
	0xf5, 0xd0, 0xc1, 0xee, 0x83, 0xc1, 0xd8, 0xb5, 0xdb, 0xbd, 0x78, 0x89, 0xd7, 0x19, 0x52, 0xbb,
	0x38, 0xca, 0x20, 0xf9, 0xbe, 0xfb, 0x1e, 0x43, 0x76, 0xd2, 0xe4, 0xa6, 0xe7, 0xf7, 0x3c, 0xb2,
	0x91, 0x04, 0x0b, 0xa3, 0x48, 0x7d, 0x19, 0x9b, 0x69, 0xbf, 0xbb, 0x78, 0x47, 0x4e, 0x42, 0x47,
	0x36, 0xbf, 0x09, 0x8c, 0x9f, 0x8d, 0xbf, 0x38, 0x4f, 0x72, 0x0e, 0x89, 0xc9, 0x50, 0xac, 0xc5,
	0x76, 0x78, 0x48, 0x4c, 0x26, 0x25, 0x0c, 0xac, 0x3a, 0x6b, 0x4c, 0xd6, 0x62, 0x3b, 0x3d, 0x84,
	0x9a, 0x59, 0x6a, 0xa8, 0xc2, 0xff, 0x91, 0x71, 0x2d, 0x11, 0xc6, 0xa9, 0x2b, 0x2d, 0xf9, 0x0a,
	0x07, 0x01, 0xb7, 0x92, 0xd3, 0xfc, 0x17, 0x0e, 0x63, 0x9a, 0xeb, 0xc0, 0x52, 0xe5, 0x70, 0xd4,
	0xb0, 0x54, 0x39, 0xb9, 0x82, 0x49, 0xae, 0xc8, 0x50, 0x99, 0x69, 0x1c, 0xaf, 0xc5, 0x56, 0x1c,
	0xae, 0x5a, 0x3e, 0xc0, 0x34, 0x77, 0xf6, 0x14, 0xcd, 0x49, 0x30, 0x3b, 0xc0, 0x9d, 0x2a, 0x6f,
	0x3a, 0xa7, 0xb1, 0xb3, 0xd5, 0xec, 0x91, 0x39, 0xeb, 0xda, 0x59, 0x8d, 0x10, 0x7e, 0xbb, 0x6a,
	0xb9, 0x87, 0xbb, 0x4c, 0x55, 0xb9, 0x39, 0x7d, 0xd3, 0xb1, 0x50, 0x3f, 0xc6, 0x9e, 0x8a, 0x23,
	0x9b, 0x38, 0x0b, 0xc1, 0x65, 0x6b, 0xbe, 0x47, 0xef, 0xc3, 0x9c, 0x35, 0xef, 0x87, 0x6a, 0xbc,
	0x09, 0x81, 0x84, 0x6a, 0x9e, 0x84, 0xaa, 0x8b, 0xc6, 0xdb, 0x38, 0x09, 0xd7, 0xf2, 0x1e, 0x46,
	0x85, 0x2b, 0x7d, 0xaa, 0x71, 0x1e, 0x68, 0xa3, 0x36, 0x2b, 0x18, 0xbc, 0xb5, 0xd3, 0xf3, 0x46,
	0x44, 0xb7, 0x91, 0xfd, 0x0b, 0xf4, 0x2e, 0x22, 0x9f, 0x60, 0xf6, 0xaa, 0xa9, 0xb9, 0x49, 0x21,
	0x17, 0xbb, 0xde, 0xfd, 0xf8, 0x89, 0xd5, 0xb2, 0x4f, 0x9a, 0xdc, 0xe6, 0xdf, 0xe7, 0x28, 0x1c,
	0xf7, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x13, 0x4f, 0x33, 0x26, 0xf0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IatafinderClient is the client API for Iatafinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IatafinderClient interface {
	GetAirports(ctx context.Context, in *Iata, opts ...grpc.CallOption) (*Airport, error)
}

type iatafinderClient struct {
	cc *grpc.ClientConn
}

func NewIatafinderClient(cc *grpc.ClientConn) IatafinderClient {
	return &iatafinderClient{cc}
}

func (c *iatafinderClient) GetAirports(ctx context.Context, in *Iata, opts ...grpc.CallOption) (*Airport, error) {
	out := new(Airport)
	err := c.cc.Invoke(ctx, "/iatafinder.iatafinder/GetAirports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IatafinderServer is the server API for Iatafinder service.
type IatafinderServer interface {
	GetAirports(context.Context, *Iata) (*Airport, error)
}

func RegisterIatafinderServer(s *grpc.Server, srv IatafinderServer) {
	s.RegisterService(&_Iatafinder_serviceDesc, srv)
}

func _Iatafinder_GetAirports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Iata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IatafinderServer).GetAirports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iatafinder.iatafinder/GetAirports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IatafinderServer).GetAirports(ctx, req.(*Iata))
	}
	return interceptor(ctx, in, info, handler)
}

var _Iatafinder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iatafinder.iatafinder",
	HandlerType: (*IatafinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAirports",
			Handler:    _Iatafinder_GetAirports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iatafinder.proto",
}
