# network refers to what network protocol; such as tcp or udp
network="tcp"
# IP refers to the ip that the service should be listening on
ip="0.0.0.0"
# The port specifies where the service should listen and for rpc is default 50051
port="50051"